version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@super-linter-api-maintainers"
    assignees:
      - "@super-linter-api-maintainers"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore patch updates for stable packages
      - dependency-name: "express"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "winston"
        update-types: ["version-update:semver-patch"]
    groups:
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "@types/*"
      testing:
        patterns:
          - "jest"
          - "@types/jest"
          - "ts-jest"
          - "supertest"
          - "@types/supertest"
      build-tools:
        patterns:
          - "tsx"
          - "nodemon"
          - "eslint"
          - "prettier"

  # Enable version updates for Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@super-linter-api-maintainers"
    assignees:
      - "@super-linter-api-maintainers"
    commit-message:
      prefix: "docker"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@super-linter-api-maintainers"
    assignees:
      - "@super-linter-api-maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "actions/*"
          - "docker/*"